### ISSUE TITLE
unknown attribute: description

### ISSUE THREAD

**Issue by gyermich** [merit-gem/merit#157]
I am getting `ActiveRecord::UnknownAttributeError: description` when trying to grant a badge to user on sign up. My terminal output:

```
 (0.6ms)  BEGIN
  User Exists (0.9ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" = 'kjhkjhk@mail.com' LIMIT 1
  SQL (52.1ms)  INSERT INTO "users" ("bio", "city", "created_at", "email", "encrypted_password", "name", "updated_at", "zipcode") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["bio", "654654"], ["city", "kjhkjh"], ["created_at", Fri, 11 Apr 2014 19:31:01 UTC +00:00], ["email", "kjhkjhk@mail.com"], ["encrypted_password", "$2a$10$fWX//35zRUylbDLEOj2jMO8wb9nfiboeaII4mE337wbqmlo6AvZZK"], ["name", "jhjkh"], ["updated_at", Fri, 11 Apr 2014 19:31:01 UTC +00:00], ["zipcode", "65465"]]
   (6.9ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (7.4ms)  UPDATE "users" SET "last_sign_in_at" = $1, "current_sign_in_at" = $2, "last_sign_in_ip" = $3, "current_sign_in_ip" = $4, "sign_in_count" = $5, "updated_at" = $6 WHERE "users"."id" = 24  [["last_sign_in_at", Fri, 11 Apr 2014 19:31:01 UTC +00:00], ["current_sign_in_at", Fri, 11 Apr 2014 19:31:01 UTC +00:00], ["last_sign_in_ip", "127.0.0.1"], ["current_sign_in_ip", "127.0.0.1"], ["sign_in_count", 1], ["updated_at", Fri, 11 Apr 2014 19:31:01 UTC +00:00]]
   (0.5ms)  COMMIT
Redirected to http://localhost:3000/
[merit] No object found, maybe you need a '@registration' variable in 'users/registrations_controller'?
[merit] No object found, maybe you need a '@registration' variable in 'users/registrations_controller'?
   (0.4ms)  BEGIN
  SQL (1.6ms)  INSERT INTO "merit_actions" ("action_method", "created_at", "target_model", "updated_at", "user_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["action_method", "create"], ["created_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00], ["target_model", "users/registrations"], ["updated_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00], ["user_id", 24]]
   (5.5ms)  COMMIT
  Merit::Action Load (0.9ms)  SELECT "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = 'f'
   (0.3ms)  BEGIN
  SQL (0.9ms)  UPDATE "merit_actions" SET "processed" = $1, "updated_at" = $2 WHERE "merit_actions"."id" = 13  [["processed", true], ["updated_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00]]
   (6.5ms)  COMMIT
  User Load (0.9ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT 1
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = 24 LIMIT 1
   (0.2ms)  BEGIN
  SQL (1.3ms)  INSERT INTO "sashes" ("created_at", "updated_at") VALUES ($1, $2) RETURNING "id"  [["created_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00], ["updated_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00]]
  SQL (0.9ms)  INSERT INTO "merit_scores" DEFAULT VALUES RETURNING "id"
  SQL (0.9ms)  UPDATE "merit_scores" SET "sash_id" = $1 WHERE "merit_scores"."id" = 8  [["sash_id", 8]]
   (7.9ms)  COMMIT
   (0.3ms)  BEGIN
  SQL (1.0ms)  UPDATE "users" SET "sash_id" = $1, "updated_at" = $2 WHERE "users"."id" = 24  [["sash_id", 8], ["updated_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00]]
   (0.7ms)  COMMIT
  Merit::BadgesSash Load (1.1ms)  SELECT "badges_sashes".* FROM "badges_sashes" WHERE "badges_sashes"."sash_id" = $1  [["sash_id", 8]]
   (0.2ms)  BEGIN
  SQL (1.4ms)  INSERT INTO "badges_sashes" ("badge_id", "created_at", "sash_id") VALUES ($1, $2, $3) RETURNING "id"  [["badge_id", 1], ["created_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00], ["sash_id", 8]]
   (0.5ms)  COMMIT
   (0.4ms)  BEGIN
  SQL (1.0ms)  INSERT INTO "merit_activity_logs" ("action_id", "created_at", "description", "related_change_id", "related_change_type") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["action_id", 13], ["created_at", Fri, 11 Apr 2014 19:31:02 UTC +00:00], ["description", "granted just-registered badge"], ["related_change_id", 6], ["related_change_type", "Merit::BadgesSash"]]
   (6.6ms)  COMMIT
   (0.5ms)  BEGIN
   (0.5ms)  ROLLBACK
Completed 500 Internal Server Error in 421ms

ActiveRecord::UnknownAttributeError - unknown attribute: description:
  activerecord (4.0.2) lib/active_record/attribute_assignment.rb:47:in `rescue in _assign_attribute'
  activerecord (4.0.2) lib/active_record/attribute_assignment.rb:42:in `_assign_attribute'
  activerecord (4.0.2) lib/active_record/attribute_assignment.rb:29:in `block in assign_attributes'
  activerecord (4.0.2) lib/active_record/attribute_assignment.rb:23:in `assign_attributes'
  activerecord (4.0.2) lib/active_record/persistence.rb:229:in `block in update'
  activerecord (4.0.2) lib/active_record/transactions.rb:326:in `block in with_transaction_returning_status'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `block in transaction'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:210:in `within_new_transaction'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/database_statements.rb:202:in `transaction'
  activerecord (4.0.2) lib/active_record/transactions.rb:209:in `transaction'
  activerecord (4.0.2) lib/active_record/transactions.rb:323:in `with_transaction_returning_status'
  activerecord (4.0.2) lib/active_record/persistence.rb:228:in `update'
  /Users/Gala/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/observer.rb:195:in `block in notify_observers'
  /Users/Gala/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/observer.rb:194:in `notify_observers'
  merit (2.1.0) lib/merit/judge.rb:96:in `notify_observers'
  merit (2.1.0) lib/merit/judge.rb:43:in `block in grant_badges'
  merit (2.1.0) lib/merit/judge.rb:40:in `grant_badges'
  merit (2.1.0) lib/merit/judge.rb:19:in `apply_badges'
  merit (2.1.0) app/models/merit/action.rb:35:in `block in check_rules'
  merit (2.1.0) app/models/merit/action.rb:33:in `check_rules'
  merit (2.1.0) app/models/merit/action.rb:26:in `check_all_rules'
  activerecord (4.0.2) lib/active_record/relation/delegation.rb:13:in `map'
  merit (2.1.0) app/models/merit/action.rb:18:in `check_unprocessed'
  merit (2.1.0) lib/merit/controller_extensions.rb:10:in `block in included'
  activesupport (4.0.2) lib/active_support/callbacks.rb:426:in `_run__3282140248608317188__process_action__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `block in instrument'
  activesupport (4.0.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.0.2) lib/active_support/notifications.rb:159:in `instrument'
  actionpack (4.0.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.0.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
  activerecord (4.0.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.0.2) lib/abstract_controller/base.rb:136:in `process'
  actionpack (4.0.2) lib/abstract_controller/rendering.rb:44:in `process'
  actionpack (4.0.2) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.0.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.0.2) lib/action_controller/metal.rb:231:in `block in action'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:48:in `call'
  actionpack (4.0.2) lib/action_dispatch/routing/mapper.rb:44:in `call'
  actionpack (4.0.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
  actionpack (4.0.2) lib/action_dispatch/journey/router.rb:59:in `call'
  actionpack (4.0.2) lib/action_dispatch/routing/route_set.rb:680:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:35:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/flash.rb:241:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/cookies.rb:486:in `call'
  activerecord (4.0.2) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.0.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
  activerecord (4.0.2) lib/active_record/migration.rb:369:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.0.2) lib/active_support/callbacks.rb:373:in `_run__2953040036961088524__call__callbacks'
  activesupport (4.0.2) lib/active_support/callbacks.rb:80:in `run_callbacks'
  actionpack (4.0.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/reloader.rb:64:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `block in tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:25:in `tagged'
  activesupport (4.0.2) lib/active_support/tagged_logging.rb:67:in `tagged'
  railties (4.0.2) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.2) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.0.2) lib/action_dispatch/middleware/static.rb:64:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.2) lib/rails/engine.rb:511:in `call'
  railties (4.0.2) lib/rails/application.rb:97:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /Users/Gala/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
  /Users/Gala/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
  /Users/Gala/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

My schema:

``` ruby
create_table "badges_sashes", force: true do |t|
    t.integer  "badge_id"
    t.integer  "sash_id"
    t.boolean  "notified_user", default: false
    t.datetime "created_at"
  end

  add_index "badges_sashes", ["badge_id", "sash_id"], name: "index_badges_sashes_on_badge_id_and_sash_id", using: :btree
  add_index "badges_sashes", ["badge_id"], name: "index_badges_sashes_on_badge_id", using: :btree
  add_index "badges_sashes", ["sash_id"], name: "index_badges_sashes_on_sash_id", using: :btree

  create_table "categories", force: true do |t|
    t.string   "name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "merit_actions", force: true do |t|
    t.integer  "user_id"
    t.string   "action_method"
    t.integer  "action_value"
    t.boolean  "had_errors",    default: false
    t.string   "target_model"
    t.integer  "target_id"
    t.boolean  "processed",     default: false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "merit_activity_logs", force: true do |t|
    t.integer  "action_id"
    t.string   "related_change_type"
    t.integer  "related_change_id"
    t.string   "description"
    t.datetime "created_at"
  end

  create_table "merit_score_points", force: true do |t|
    t.integer  "score_id"
    t.integer  "num_points", default: 0
    t.string   "log"
    t.datetime "created_at"
  end

  create_table "merit_scores", force: true do |t|
    t.integer "sash_id"
    t.string  "category", default: "default"
  end

  create_table "rates", force: true do |t|
    t.integer  "rater_id"
    t.integer  "rateable_id"
    t.string   "rateable_type"
    t.float    "stars",         null: false
    t.string   "dimension"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "rates", ["rateable_id", "rateable_type"], name: "index_rates_on_rateable_id_and_rateable_type", using: :btree
  add_index "rates", ["rater_id"], name: "index_rates_on_rater_id", using: :btree

  create_table "rating_caches", force: true do |t|
    t.integer  "cacheable_id"
    t.string   "cacheable_type"
    t.float    "avg",            null: false
    t.integer  "qty",            null: false
    t.string   "dimension"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "rating_caches", ["cacheable_id", "cacheable_type"], name: "index_rating_caches_on_cacheable_id_and_cacheable_type", using: :btree

  create_table "sashes", force: true do |t|
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "task_categories", force: true do |t|
    t.integer  "task_id"
    t.integer  "category_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tasks", force: true do |t|
    t.integer  "owner_id"
    t.boolean  "paid",        default: false
    t.float    "pay"
    t.string   "status",      default: "pending"
    t.string   "summary"
    t.string   "name"
    t.date     "due_date"
    t.time     "due_time"
    t.integer  "num_workers", default: 1
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "user_categories", force: true do |t|
    t.integer  "user_id"
    t.integer  "category_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "user_tasks", force: true do |t|
    t.integer  "user_id"
    t.integer  "task_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "accept",     default: false
  end

  create_table "users", force: true do |t|
    t.string   "name"
    t.string   "email"
    t.string   "city"
    t.string   "zipcode"
    t.text     "bio"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.string   "image"
    t.integer  "sash_id"
    t.integer  "level",                  default: 0
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree
```

**Comment by roadev** [comment]
Hey guys, could you help me with this?
http://stackoverflow.com/questions/31758478/merit-doesnt-add-points-to-user-after-create-action
