### ISSUE TITLE
undefined method `after_filter' for ActionController::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by emaillenin** [merit-gem/merit#274]
I am using merit gem version 2.4.0 and rails 5.1.1. I am getting the following error on rails startup:

````
/Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/merit-2.4.0/lib/merit/controller_extensions.rb:7:in `included': undefined method `after_filter' for ActionController::Base:Class (NoMethodError)
Did you mean?  after_action
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/merit-2.4.0/lib/merit.rb:90:in `include'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/merit-2.4.0/lib/merit.rb:90:in `block (2 levels) in <class:Engine>'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:35:in `block in on_load'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:34:in `each'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/lazy_load_hooks.rb:34:in `on_load'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/merit-2.4.0/lib/merit.rb:85:in `block in <class:Engine>'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/initializable.rb:30:in `run'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/lenin.rajasekaran/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/initializable.rb:58:in `run_initializers'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/application.rb:353:in `initialize!'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `public_send'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/railtie.rb:185:in `method_missing'
	from /Users/lenin.rajasekaran/Dropbox/Projects/duggout/duggout/config/environment.rb:5:in `<top (required)>'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/activesupport-5.1.1/lib/active_support/dependencies.rb:292:in `require'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/application.rb:329:in `require_environment!'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/command/actions.rb:16:in `require_application_and_environment!'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/commands/console/console_command.rb:84:in `perform'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/command/base.rb:63:in `perform'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/command.rb:44:in `invoke'
	from /Users/lenin.rajasekaran/.rvm/gems/ruby-2.3.1@duggout-app/gems/railties-5.1.1/lib/rails/commands.rb:16:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
````

My Gemfile:

````
source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails', '~> 5.1.1'
gem 'pg'
gem 'paperclip', '4.3.1'
gem 'font-awesome-rails', '~> 4.7.0.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5.0'
gem 'jquery-turbolinks'
gem 'jquery-ui-rails', '= 6.0.1'
gem 'devise', '~> 4.3'
gem 'merit', '~> 2'
gem 'redis', '~> 3.2.2'
gem 'omniauth', '~> 1.6'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'
gem 'slim-rails', '~> 3.1'
gem 'meta-tags'
gem 'pundit'
gem 'httpclient'
gem 'psych', '2.0.5'
gem 'twitter'
gem 'require_all'
gem 'activeadmin', '= 1.0.0'
gem 'sass'
gem "compass-rails", github: "compass/compass-rails", branch: "master"group, not in assets
gem 'httparty'
gem 'oj'
gem 'oj_mimic_json'
gem 'database_cleaner'
gem 'chronic'
gem 'rabl'
gem 'momentjs-rails'
gem 'fullcalendar-rails'
gem 'redis-objects', github: "nateware/redis-objects", branch: "master"
gem 'connection_pool'
gem 'sidekiq', '~> 4.2'
gem 'gcm', require: false
gem 'rollbar'
gem 'chartkick', :require => true
gem 'payuindia', :git => 'git://github.com/payu-india/payuindia.git'
gem 'google-id-token'
gem 'phony', require: false
gem 'jwt'
gem 'sendgrid-ruby',
gem 'newrelic_rpm'
gem 'aws-sdk', '< 2.0'
gem 'bulk_insert'
gem 'koala', require: false
gem 'acts_as_commentable'
gem 'puma', '= 3.8.2'
group :doc do
  gem 'sdoc', require: false
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'rspec-rails', '~> 3.5'
  gem 'brakeman', :require => false
end

group :test do
  gem 'timecop'
  gem 'webmock', require: false
end

group :development, :test do
  gem 'bullet'
  gem 'factory_girl_rails', '~> 4.5.0'
  gem 'pry'
end

group :assets do
  gem 'uglifier', '>= 1.3.0'
end

````

**Comment by tute** [comment]
It looks like the `base.respond_to? :after_action` condition doesn't work in Rails 5.1.1? That smells like a bug in https://github.com/merit-gem/merit/blob/dc870272c1f68bf0e6e6669e27aa4a5675a3a855/lib/merit/controller_extensions.rb#L7.

Thanks for reporting!

**Comment by DLawla** [comment]
Just to follow up and affirm your assumption, @tute -- I ran into the same issue (Rails 5.1) above and forked the repo to comment out the whole `base.respond_to? :after_action` check to just `base.after_action :log_and_process`. I then had no issues.

It's a weird one.

**Comment by sofarsophie** [comment]
I'm also having this issue. The gem worked fine last week but when I restarted the server today, I got the error.

**Comment by tute** [comment]
About to release v3 of merit, you may upgrade to get rid of this error. Thanks!

**Comment by DLawla** [comment]
Awesome. Good work!

Dan Lawler
