### ISSUE TITLE
Nothing happened on Rails 5.2

### ISSUE THREAD

**Issue by truongnmt** [merit-gem/merit#294]
I'm using Rails 5.2, Merit 3.0.1

This is my setup:
`rails g merit:install`
`rails g merit user`
`rake db:migrate`

I use only `point` system so this is my `point_rules.rb` setting:
```ruby
def initialize
  score 1, on: 'todos#create'
  score 1, on: 'todos#create123123'
  score 1, on: 'todos#create', to: [:user]
  score 1, on: 'todos#create', to: [:user123123]
  score 5, on: 'todos#update', to: [:user] do |todo|
    todo.state == 1
  end
  score -1, on: 'todos#destroy', to: [:user]
end
```
Yeah some of this is silly but still I dont see any thing about Merit in server log :((
```
Started POST "/todos" for 127.0.0.1 at 2018-06-24 21:25:26 +0700
Processing by TodosController#create as JS
  Parameters: {"utf8"=>"✓", "todo"=>{"content"=>"asdfasdf", "due"=>"2018-06-24"}}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
  ↳ /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
   (0.2ms)  begin transaction
  ↳ app/controllers/todos_controller.rb:21
  Todo Create (0.4ms)  INSERT INTO "todos" ("content", "due", "created_at", "updated_at", "user_id") VALUES (?, ?, ?, ?, ?)  [["content", "asdfasdf"], ["due", "2018-06-24"], ["created_at", "2018-06-24 14:25:26.275302"], ["updated_at", "2018-06-24 14:25:26.275302"], ["user_id", 3]]
  ↳ app/controllers/todos_controller.rb:21
   (8.1ms)  commit transaction
  ↳ app/controllers/todos_controller.rb:21
  Rendering todos/create.js.erb
  Rendered todos/_todo.html.erb (1.3ms)
  Rendered todos/create.js.erb (5.5ms)
Completed 200 OK in 42ms (Views: 19.0ms | ActiveRecord: 9.0ms)


Started PATCH "/todos/926" for 127.0.0.1 at 2018-06-24 21:28:45 +0700
Processing by TodosController#update as JS
  Parameters: {"utf8"=>"✓", "todo"=>{"state"=>"1"}, "button"=>"", "id"=>"926"}
  Todo Load (0.2ms)  SELECT  "todos".* FROM "todos" WHERE "todos"."id" = ? LIMIT ?  [["id", 926], ["LIMIT", 1]]
  ↳ app/controllers/todos_controller.rb:52
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
  ↳ /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
   (0.2ms)  begin transaction
  ↳ app/controllers/todos_controller.rb:29
  User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  ↳ app/controllers/todos_controller.rb:29
  Todo Update (0.6ms)  UPDATE "todos" SET "state" = ?, "updated_at" = ? WHERE "todos"."id" = ?  [["state", 1], ["updated_at", "2018-06-24 14:28:45.370874"], ["id", 926]]
  ↳ app/controllers/todos_controller.rb:29
   (8.6ms)  commit transaction
  ↳ app/controllers/todos_controller.rb:29
  Rendering todos/update.js.erb
  Rendered todos/_todo.html.erb (2.1ms)
  Rendered todos/update.js.erb (7.1ms)
Completed 200 OK in 79ms (Views: 34.6ms | ActiveRecord: 10.9ms)


Started DELETE "/todos/928" for 127.0.0.1 at 2018-06-24 21:29:50 +0700
Processing by TodosController#destroy as JS
  Parameters: {"id"=>"928"}
  Todo Load (0.2ms)  SELECT  "todos".* FROM "todos" WHERE "todos"."id" = ? LIMIT ?  [["id", 928], ["LIMIT", 1]]
  ↳ app/controllers/todos_controller.rb:52
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
  ↳ /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-5.2.0/lib/active_record/log_subscriber.rb:98
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  ↳ app/controllers/todos_controller.rb:37
   (0.4ms)  begin transaction
  ↳ app/controllers/todos_controller.rb:38
  Todo Destroy (0.8ms)  DELETE FROM "todos" WHERE "todos"."id" = ?  [["id", 928]]
  ↳ app/controllers/todos_controller.rb:38
   (8.9ms)  commit transaction
  ↳ app/controllers/todos_controller.rb:38
  Rendering todos/destroy.js.erb
  Rendered todos/destroy.js.erb (0.4ms)
Completed 200 OK in 41ms (Views: 12.3ms | ActiveRecord: 10.9ms)
```

When I test on console, user's point is 0
```
[8] pry(main)> User.find(3).points
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  Merit::Sash Load (0.2ms)  SELECT  "sashes".* FROM "sashes" WHERE "sashes"."id" = ? LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Merit::Score Load (0.3ms)  SELECT "merit_scores".* FROM "merit_scores" WHERE "merit_scores"."sash_id" = ?  [["sash_id", 1]]
   (0.3ms)  SELECT SUM("merit_score_points"."num_points") AS sum_num_points, "merit_score_points"."score_id" AS merit_score_points_score_id FROM "merit_score_points" WHERE "merit_score_points"."score_id" = ? GROUP BY "merit_score_points"."score_id"  [["score_id", 1]]
=> 0
```

I guess just a silly error on somewhere @@

**Comment by tute** [comment]
Hi! It's indeed strange, at the least it should create `Merit::Action` models. Can you share your `merit.rb` initializer file please? Is your code available somewhere where I can check it?

**Comment by truongnmt** [comment]
@tute 
Well in [merit.rb](https://github.com/truongnmt/DoIt/commit/74756a92462450aeb66d6ab8bf905af92d166843#diff-16783f298e1075d43762c97cb5261012) I don't config anything.

Full commit to add merit in [here](https://github.com/truongnmt/DoIt/commit/74756a92462450aeb66d6ab8bf905af92d166843)

**Comment by truongnmt** [comment]
Okay let me see.

**Comment by truongnmt** [comment]
@tute Why I got error on running rake :( can you have a look. I'm still beginner tho
```
/Users/truongnm/.rbenv/versions/2.5.0/bin/ruby -w -I"lib:lib:test" -I"/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib" "/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "test/integration/navigation_test.rb" "test/unit/action_test.rb" "test/unit/base_target_finder_test.rb" "test/unit/merit_unit_test.rb" "test/unit/rule_unit_test.rb" "test/unit/rules_matcher_test.rb" "test/unit/sash_finder_test.rb" "test/unit/sash_test.rb" "test/unit/score_test.rb" "test/unit/target_finder_test.rb"
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: method redefined; discarding old first
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: previous definition of first was here
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: method redefined; discarding old count
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: previous definition of count was here
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: method redefined; discarding old find
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/forwardable.rb:220: warning: previous definition of find was here
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ambry-1.0.0/lib/ambry/model.rb:85: warning: method redefined; discarding old mapper
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ambry-1.0.0/lib/ambry/model.rb:86: warning: instance variable @mapper not initialized
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ambry-1.0.0/lib/ambry/model.rb:87: warning: instance variable @adapter_name not initialized
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/ambry-1.0.0/lib/ambry/model.rb:88: warning: instance variable @mapper_options not initialized
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.18.1/lib/thor/base.rb:593: warning: instance variable @no_commands not initialized
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.18.1/lib/thor.rb:382: warning: instance variable @long_desc not initialized
Mocha deprecation warning at /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require': `require 'mocha/mini_test'` has been deprecated. Please use `require 'mocha/minitest' instead.
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/addressable-2.5.2/lib/addressable/idna/pure.rb:154: warning: assigned but unused variable - startercc
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.18.1/lib/thor/actions/directory.rb:92: warning: assigned but unused variable - destination
Traceback (most recent call last):
	8: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:63:in `block in autorun'
	7: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:123:in `run'
	6: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:169:in `process_args'
	5: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:169:in `new'
	4: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/2.5.0/optparse.rb:1062:in `initialize'
	3: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:201:in `block in process_args'
	2: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:201:in `each'
	1: from /Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/minitest-5.11.3/lib/minitest.rb:203:in `block (2 levels) in process_args'
/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/minitest/rails_plugin.rb:16:in `plugin_rails_options': uninitialized constant Minitest::Rails::TestUnit (NameError)
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib" "/Users/truongnm/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.1/lib/rake/rake_test_loader.rb" "test/integration/navigation_test.rb" "test/unit/action_test.rb" "test/unit/base_target_finder_test.rb" "test/unit/merit_unit_test.rb" "test/unit/rule_unit_test.rb" "test/unit/rules_matcher_test.rb" "test/unit/sash_finder_test.rb" "test/unit/sash_test.rb" "test/unit/score_test.rb" "test/unit/target_finder_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by tute** [comment]
> It said I have something wrong with Minitest I guess.

It seems like. How did you run the tests? The commands I suggest to set it up is, after cloning the repo, and while being in that directory:

```
bundle install
bundle exec rake
```

Does that work? Can you copy the entire session (alongside the command you write)? What version of Ruby are you using?

Thanks for your help!

**Comment by truongnmt** [comment]
@tute I'm running as your instruction in CONTRIBUTION.md
The full log is in this [gist](https://gist.github.com/truongnmt/5a192480691e5b27f167d816876bebfc).
I'm using `ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]`.

**Comment by tute** [comment]
ah, thanks for the detailed gist.

This is a known bug in Rails, corrected in master: https://github.com/rails/rails/issues/31324. Because of how https://github.com/merit-gem/merit/blob/master/Gemfile#L5-L10 is written, setting `RAILS_VERSION=5.2` is required now (although the software doesn't fail if you don't set it).

What happens, then, if you run:

```
export RAILS_VERSION=5.2
bundle install
bundle exec rake
```

**Comment by jamesjefferies** [comment]
@truongnmt I had your same issue and resolved it by ensuring I was definitely on the latest stable Rails 5.2 branch - you may need to set RAILS_VERSION=5.2 as an environment variable, I simply commented that bit out temporarily, hence 

```
 gem 'rails', github: "rails/rails", branch: "5-2-stable"
```

**Comment by tute** [comment]
Right, thank you @jamesjefferies

**Comment by truongnmt** [comment]
Oh gosh, thanks for detail reply, @tute @jamesjefferies
I'm still beginner tho :))

**Comment by tute** [comment]
> Sorry I'm still beginner tho :))

It's good to know, I'll help as good I can! :)

**Comment by truongnmt** [comment]
@jamesjefferies Can you work on this PR, I'm still looking for a way to solve 
* `warning: already initialized constant Merit::AppBadgeRules` 
* `warning: already initialized constant Merit::AppPointRules` 

but still no success yet.

**Comment by jamesjefferies** [comment]
@truongnmt #297 see if this does the trick for you...

**Comment by tute** [comment]
Closing this issue in favor of the PR. Again, thank you both! 😃
