### ISSUE TITLE
Broken for Rails 4.2:  Unknown key: :optional. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :dependent, :primary_key, :inverse_of, :required, :foreign_type, :polymorphic, :touch, :counter_cache (ArgumentError)

### ISSUE THREAD

**Issue by starrychloe** [merit-gem/merit#301]
```
>rails g merit:install
C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys': Unknown key: :optional. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :dependent, :primary_key, :inverse_of, :required, :foreign_type, :polymorphic, :touch, :counter_cache (ArgumentError)
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/keys.rb:73:in `each_key'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/core_ext/hash/keys.rb:73:in `assert_valid_keys'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:82:in `validate_options'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:62:in `initialize'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:47:in `new'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:47:in `create_builder'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations/builder/association.rb:35:in `build'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activerecord-4.2.3/lib/active_record/associations.rb:1515:in `belongs_to'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/merit-3.0.2/lib/merit/models/active_record/merit/activity_log.rb:6:in `<class:ActivityLog>'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/merit-3.0.2/lib/merit/models/active_record/merit/activity_log.rb:2:in `<module:Merit>'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/merit-3.0.2/lib/merit/models/active_record/merit/activity_log.rb:1:in `<top (required)>'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/merit-3.0.2/lib/merit.rb:102:in `require_models'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/merit-3.0.2/lib/merit.rb:84:in `block in <class:Engine>'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from C:/ruby23/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
        from C:/Users/Chloe/workspace/medictests/config/environment.rb:5:in `<top (required)>'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in `generate'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/ruby23/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

```
>rails -v
Rails 4.2.3
```

**Comment by redtachyons** [comment]
Rails 4.2 is no longer supported, you will have to use previous versions of merrit to use with rails < 5.x

**Comment by tute** [comment]
That's right, we dropped support for Rails version <5 in 3.0 release. See https://github.com/merit-gem/merit/blob/master/NEWS.md#300. Thanks!

**Comment by snmmaurya** [comment]
we can use optional: true only with belongs_to method
