### ISSUE TITLE
Cannot install on model with existing property: PG::DuplicateColumn: ERROR:  column "level" of relation "users" already exists

### ISSUE THREAD

**Issue by starrychloe** [merit-gem/merit#302]
I already have a `user.level` field. It should not modify the model or touch model fields except to add the `belongs_to` / `has_one` relation. All additional fields should go in the merit relation model.

```
== 20180805005720 AddMeritFieldsToUsers: migrating ============================
-- add_column(:users, :sash_id, :integer)
   -> 0.0011s
-- add_column(:users, :level, :integer, {:default=>0})
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "level" of relation "users" already exists
: ALTER TABLE "users" ADD "level" integer DEFAULT 0
C:/Users/Chloe/workspace/medictests/db/migrate/20180805005720_add_merit_fields_to_users.rb:4:in `change'
C:in `migrate'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "level" of relation "users" already exists
: ALTER TABLE "users" ADD "level" integer DEFAULT 0
C:/Users/Chloe/workspace/medictests/db/migrate/20180805005720_add_merit_fields_to_users.rb:4:in `change'
C:in `migrate'

Caused by:
PG::DuplicateColumn: ERROR:  column "level" of relation "users" already exists
C:/Users/Chloe/workspace/medictests/db/migrate/20180805005720_add_merit_fields_to_users.rb:4:in `change'
C:in `migrate'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Using Merit version 2.4.0.

**Comment by tute** [comment]
Agreed, thanks for your report. Will leave open, happy to help anyone who would like to work on a PR! :-)

**Comment by tute** [comment]
AFAIK this hasn't been an issue to other people yet. While having the `level` attribute prefixed with the name of the gem or in the `sashes` table would be cleaner, if it's not a problem people encounter while using merit I will close for now.
