### ISSUE TITLE
Cannot use symbols as names: Merit::BadgeNotFound (No badge 'question_report' found. Define it in initializers/merit.rb)

### ISSUE THREAD

**Issue by starrychloe** [merit-gem/merit#303]
Using symbols as names produces an error, even though using symbols is the logical thing to do.

    Merit::Badge.create! id: id+=1, name: :question_report, description: "You reported a problem with a question!"

and

    grant_on 'question_tickets#create', badge: :question_report

produces

```
Completed 500 Internal Server Error in 217ms (Views: 0.7ms | ActiveRecord: 123.1ms)

Merit::BadgeNotFound (No badge 'question_report' found. Define it in initializers/merit.rb):
  merit (2.4.0) app/models/merit/badge.rb:43:in `find_by_name_and_level'
  merit (2.4.0) lib/merit/rule.rb:31:in `badge'
  merit (2.4.0) lib/merit/judge.rb:90:in `badge'
  merit (2.4.0) lib/merit/judge.rb:62:in `new_or_multiple?'
  merit (2.4.0) lib/merit/judge.rb:41:in `block in grant_badges'
  merit (2.4.0) lib/merit/judge.rb:40:in `each'
  merit (2.4.0) lib/merit/judge.rb:40:in `grant_badges'
  merit (2.4.0) lib/merit/judge.rb:19:in `apply_badges'
  merit (2.4.0) app/models/merit/action.rb:35:in `block in check_rules'
  merit (2.4.0) app/models/merit/action.rb:33:in `each'
  merit (2.4.0) app/models/merit/action.rb:33:in `check_rules'
  merit (2.4.0) app/models/merit/action.rb:26:in `check_all_rules'
  C:in `map'
  C:in `map'
  merit (2.4.0) app/models/merit/action.rb:18:in `check_unprocessed'
  merit (2.4.0) lib/merit/controller_extensions.rb:10:in `block in included'
  activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `instance_exec'
  activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:237:in `block in halting'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `each'
  activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  rack-mini-profiler (1.0.0) lib/mini_profiler/profiling_methods.rb:104:in `block in profile_method'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
  rack (1.6.10) lib/rack/etag.rb:24:in `call'
  rack (1.6.10) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.10) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.10) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.10) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.10) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  rack-mini-profiler (1.0.0) lib/mini_profiler/profiler.rb:285:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.10) lib/rack/lock.rb:17:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  rack (1.6.10) lib/rack/handler/webrick.rb:88:in `service'
  C:/ruby23/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  C:/ruby23/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  C:/ruby23/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

Merit version 2.4

**Comment by tute** [comment]
@dzcar fixed this in https://github.com/merit-gem/merit/pull/306. Thank you both!
