### ISSUE TITLE
Granting badges with Devise Registrations#update not working

### ISSUE THREAD

**Issue by gabrielguerin** [merit-gem/merit#347]
I have followed [this tutorial](https://github.com/merit-gem/merit/wiki/How-to-grant-badges-on-user-using-Devise) and I am able to grant badges to new users when they are registering. However, I am trying to grant badges to users that add a description but nothing seems to happen. What have I done wrong?
```
# merit.rb
Merit::Badge.create!(
  id: 49,
  name:  'Autobiographe',
  description: 'Compléter la partie "À propos" du profil.',
  level: 1,
  custom_fields: {
    difficulty: 'bronze'
  }
)
```

```
# badge_rules.rb
grant_on 'users/registrations#update',
         badge_id: 49,
         level: 1,
         temporary: true,
         model_name: 'User' do |user|
           user.description.length > 1
         end
```

```
# registrations_controller.rb
    def update
      # Needed for Merit
      @user = resource
      super
    end
```

```
# routes.rb
  devise_for :users, path: 'users', controllers: {
    registrations: 'users/registrations',
    invitations: 'users/invitations',
    confirmations: 'users/confirmations',
    sessions: 'users/sessions'
  }
```

Thank you in advance!

**Comment by tute** [comment]
Can you paste the logs after exercising `users/registrations#update`?

**Comment by gabrielguerin** [comment]
Here are the logs @tute 
```
  Merit::Action Create (0.6ms)  INSERT INTO "merit_actions" ("user_id", "action_method", "target_model", "target_data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["user_id", 21], ["action_method", "update"], ["target_model", "users/registrations"], ["target_data", "--- \n"], ["created_at", "2020-06-19 12:51:47.890221"], ["updated_at", "2020-06-19 12:51:47.890221"]]
   (0.3ms)  COMMIT
  Merit::Action Load (0.3ms)  SELECT "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = $1 ORDER BY "merit_actions"."id" ASC LIMIT $2  [["processed", false], ["LIMIT", 1000]]
   (0.3ms)  BEGIN
  Merit::Action Update (0.4ms)  UPDATE "merit_actions" SET "processed" = $1, "updated_at" = $2 WHERE "merit_actions"."id" = $3  [["processed", true], ["updated_at", "2020-06-19 12:51:47.903236"], ["id", 19]]
   (0.7ms)  COMMIT
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
[merit] no target_obj found on Rule#applies?
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Sash Load (0.3ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Models::ActiveRecord::BadgesSash Load (0.4ms)  SELECT "badges_sashes".* FROM "badges_sashes" WHERE "badges_sashes"."sash_id" = $1 AND "badges_sashes"."badge_id" = $2 ORDER BY "badges_sashes"."id" ASC LIMIT $3  [["sash_id", 21], ["badge_id", 49], ["LIMIT", 1]]
   (0.3ms)  BEGIN
  Merit::ActivityLog Create (1.1ms)  INSERT INTO "merit_activity_logs" ("action_id", "description", "created_at") VALUES ($1, $2, $3) RETURNING "id"  [["action_id", 19], ["description", "a retiré le badge Autobiographe"], ["created_at", "2020-06-19 12:51:47.949006"]]
   (0.5ms)  COMMIT
```

**Comment by tute** [comment]
aha, no target object found it says! I think there may be a syntax error in:

```model_name: 'User' do |user|
           user.description.length > 1
         end```

Can you post all of your badge rules file please? Or, at least, all the devise ones? Thanks!

**Comment by gabrielguerin** [comment]
```
      # Registration

      grant_on 'users/confirmations#show', badge_id: 1,
                                           model_name: 'User',
                                           to: :itself do
        User.count <= 100
      end

      # Member

      grant_on 'users/sessions#create',
               badge_id: 46,
               level: 1,
               model_name: 'User',
               to: :itself do |user|
        (Date.today - user.created_at.to_date).to_i >= 365
      end

      grant_on 'users/sessions#create',
               badge_id: 47,
               level: 2,
               model_name: 'User',
               to: :itself do |user|
        (Date.today - user.created_at.to_date).to_i >= (365 * 3)
      end

      grant_on 'users/sessions#create',
               badge_id: 48,
               level: 3,
               model_name: 'User',
               to: :itself do |user|
        (Date.today - user.created_at.to_date).to_i >= (365 * 10)
      end

      # Invitations

      grant_on 'users/invitations#create',
               badge_id: 51,
               level: 1,
               model_name: 'User',
               to: :itself do |user|
        user.invitations_count == 10
      end

      grant_on 'users/invitations#create',
               badge_id: 52,
               level: 2,
               model_name: 'User',
               to: :itself do |user|
        user.invitations_count == 25
      end

      grant_on 'users/invitations#create',
               badge_id: 53,
               level: 3,
               model_name: 'User',
               to: :itself do |user|
        user.invitations_count == 100
      end

      grant_on 'users/registrations#update',
               badge_id: 49,
               level: 1,
               temporary: true,
               model_name: 'User' do |user|
        user.description.length > 1
      end
```

**Comment by tute** [comment]
Are you missing the `to: :itself` option?

**Comment by gabrielguerin** [comment]
Ok so I added the `to: :itself` option as follows:
```
      grant_on 'users/registrations#update',
               badge_id: 49,
               level: 1,
               temporary: true,
               model_name: 'User',
               to: :itself do |user|
        user.description.length > 1
      end
```
It still doesn't work. Here is the full trace:
```
   (0.2ms)  BEGIN
  Merit::Action Create (0.3ms)  INSERT INTO "merit_actions" ("user_id", "action_method", "target_model", "target_data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["user_id", 21], ["action_method", "update"], ["target_model", "users/registrations"], ["target_data", "--- \n"], ["created_at", "2020-06-20 10:06:38.021528"], ["updated_at", "2020-06-20 10:06:38.021528"]]
   (0.3ms)  COMMIT
  Merit::Action Load (0.3ms)  SELECT "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = $1 ORDER BY "merit_actions"."id" ASC LIMIT $2  [["processed", false], ["LIMIT", 1000]]
   (0.1ms)  BEGIN
  Merit::Action Update (1.5ms)  UPDATE "merit_actions" SET "processed" = $1, "updated_at" = $2 WHERE "merit_actions"."id" = $3  [["processed", true], ["updated_at", "2020-06-20 10:06:38.030178"], ["id", 34]]
   (0.3ms)  COMMIT
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
[merit] no target_obj found on Rule#applies?
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
Completed 302 Found in 91ms (ActiveRecord: 8.4ms | Allocations: 23477)
```

**Comment by gabrielguerin** [comment]
I don't know if this is important but I am also using Devise confirmation.

**Comment by tute** [comment]
I am not 100% sure, but it might be that the `target_id` or `target_data` in `merit_actions` is not being filled properly with the user being updated. Would you try, instead of `:itself`, with `:action_user` as the `to:` option?

When you paste the logs, please also paste the first lines that specify path and params.

Let me know how it goes!

**Comment by gabrielguerin** [comment]
@tute I have changed the `to:` option to `:action_user` as you asked me but it still does not work.
Here are the logs, with the first lines that specify the path and params as requested:
```
Started PUT "/users" for ::1 at 2020-07-01 14:24:11 +0200
Processing by Users::RegistrationsController#update as HTML
  Parameters: {"authenticity_token"=>"AH5RV6zuwZhI5FA8zQI9wfkKc/Y6JUvBkOpvBdbvIgymnhj4FVh77SysfrKrlMwIn11tK/g47wJCo+63oXzVyw==", "user"=>{"first_name"=>"Gabriel", "last_name"=>"Guérin", "description"=>"sdfkjfkljfdsklfjdslkfjsd", "email"=>"gabriel.gueringg@gmail.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "current_password"=>"[FILTERED]"}, "commit"=>"Mettre à jour"}
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 21], ["LIMIT", 1]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  ↳ app/controllers/users/registrations_controller.rb:42:in `update'
   (0.3ms)  BEGIN
  ↳ app/controllers/users/registrations_controller.rb:54:in `update_resource'
  User Update (2.2ms)  UPDATE "users" SET "description" = $1, "updated_at" = $2 WHERE "users"."id" = $3  [["description", "sdfkjfkljfdsklfjdslkfjsd"], ["updated_at", "2020-07-01 12:24:11.704303"], ["id", 21]]
  ↳ app/controllers/users/registrations_controller.rb:54:in `update_resource'
   (0.4ms)  COMMIT
  ↳ app/controllers/users/registrations_controller.rb:54:in `update_resource'
  User Store (959.0ms)  {"id":21}
Redirected to http://localhost:3000/badges/gabriel-guerin/user
   (0.3ms)  BEGIN
  Merit::Action Create (1.0ms)  INSERT INTO "merit_actions" ("user_id", "action_method", "target_model", "target_data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["user_id", 21], ["action_method", "update"], ["target_model", "users/registrations"], ["target_data", "--- \n"], ["created_at", "2020-07-01 12:24:12.742910"], ["updated_at", "2020-07-01 12:24:12.742910"]]
   (0.5ms)  COMMIT
  Merit::Action Load (0.5ms)  SELECT "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = $1 ORDER BY "merit_actions"."id" ASC LIMIT $2  [["processed", false], ["LIMIT", 1000]]
   (0.3ms)  BEGIN
  Merit::Action Update (0.8ms)  UPDATE "merit_actions" SET "processed" = $1, "updated_at" = $2 WHERE "merit_actions"."id" = $3  [["processed", true], ["updated_at", "2020-07-01 12:24:12.762890"], ["id", 41]]
   (0.6ms)  COMMIT
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1  [["LIMIT", 1]]
[merit] no target_obj found on Rule#applies?
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Sash Load (0.5ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Models::ActiveRecord::BadgesSash Load (0.6ms)  SELECT "badges_sashes".* FROM "badges_sashes" WHERE "badges_sashes"."sash_id" = $1 AND "badges_sashes"."badge_id" = $2 ORDER BY "badges_sashes"."id" ASC LIMIT $3  [["sash_id", 21], ["badge_id", 49], ["LIMIT", 1]]
   (0.4ms)  BEGIN
  Merit::ActivityLog Create (4.7ms)  INSERT INTO "merit_activity_logs" ("action_id", "description", "created_at") VALUES ($1, $2, $3) RETURNING "id"  [["action_id", 41], ["description", "a retiré le badge Autobiographe"], ["created_at", "2020-07-01 12:24:12.827750"]]
   (0.4ms)  COMMIT
Completed 302 Found in 1151ms (ActiveRecord: 21.7ms | Allocations: 44912)
```

It seems the user id is the correct one but Merit still cannot find the target object. Do you have any idea why?

**Comment by gabrielguerin** [comment]
I have compared the logs with the ones from another Merit action which is working with one of Devise's controller (Invitable) based on this [solution (my code is exactly as it is in the solution)] (https://github.com/scambra/devise_invitable/issues/817) and I can't seem to find where the problem is coming from.
Here are the logs from this controller:
```
Started POST "/users/invitation" for ::1 at 2020-07-01 14:44:11 +0200
Processing by Users::InvitationsController#create as HTML
  Parameters: {"authenticity_token"=>"zCc4oz1p3l8wzTrbWtdBI9lfowdK6Udi1kPHz2h+OTT3UWwGB0NSNpJIY3LGBf+wiFnyfNVwnvhyXLjBLdkVbg==", "user"=>{"email"=>"gabrielgggmail@gmail.com"}, "commit"=>"Inviter"}
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 21], ["LIMIT", 1]]
  ↳ app/controllers/users/invitations_controller.rb:150:in `current_inviter'
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."email" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["email", "gabrielgggmail@gmail.com"], ["LIMIT", 1]]
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
  User Load (0.6ms)  SELECT "users".* FROM "users" WHERE "users"."invitation_token" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["invitation_token", "66e47eabcdad76634d543d8b3173cbe278ed32be881c5e5e404a285c7457f8b3"], ["LIMIT", 1]]
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
   (0.2ms)  BEGIN
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
  User Create (2.5ms)  INSERT INTO "users" ("email", "encrypted_password", "created_at", "updated_at", "invitation_token", "invitation_created_at", "invitation_sent_at", "invited_by_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING "id"  [["email", "gabrielgggmail@gmail.com"], ["encrypted_password", "$2a$11$LZc7FFBX8tq9kxQd.2qIkuak5aexmkPMxxwipLX2IGcSivLl7pQ5q"], ["created_at", "2020-07-01 12:44:11.581623"], ["updated_at", "2020-07-01 12:44:11.581623"], ["invitation_token", "66e47eabcdad76634d543d8b3173cbe278ed32be881c5e5e404a285c7457f8b3"], ["invitation_created_at", "2020-07-01 12:44:11.580967"], ["invitation_sent_at", "2020-07-01 12:44:11.580967"], ["invited_by_id", 21]]
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
  User Update All (0.8ms)  UPDATE "users" SET "invitations_count" = COALESCE("invitations_count", 0) + $1 WHERE "users"."id" = $2  [["invitations_count", 1], ["id", 21]]
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
   (2.4ms)  COMMIT
  ↳ app/controllers/users/invitations_controller.rb:142:in `invite_resource'
  User Store (195.3ms)  {"id":23}
    (0.4ms)  BEGIN
  Merit::Action Create (10.7ms)  INSERT INTO "merit_actions" ("user_id", "action_method", "target_model", "target_id", "target_data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING "id"  [["user_id", 21], ["action_method", "create"], ["target_model", "users/invitations"], ["target_id", 21], ["target_data", "--- !ruby/object:User\nconcise_attributes:\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: encrypted_password\n  value_before_type_cast: \"$2a$11$VckYomQ6JV3/wbCtxDt.jeAPJoDWTv7bUSfUYYYHipnqmSGPuanJu\"\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: confirmed_at\n  value_before_type_cast: 2020-06-18 13:47:05.717181000 Z\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: id\n  value_before_type_cast: 21\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invitations_count\n  value_before_type_cast: 2\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: slug\n  value_before_type_cast: gabriel-guerin\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: email\n  value_before_type_cast: gabriel.gueringg@gmail.com\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: reset_password_token\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: reset_password_sent_at\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: remember_created_at\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: confirmation_token\n  value_before_type_cast: wYEyyG5sk2kwGJanPrzd\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: confirmation_sent_at\n  value_before_type_cast: 2020-06-18 13:47:02.751050000 Z\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: unconfirmed_email\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: created_at\n  value_before_type_cast: 2020-06-18 13:47:02.750932000 Z\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: updated_at\n  value_before_type_cast: 2020-07-01 12:24:11.704303000 Z\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: first_name\n  value_before_type_cast: Gabriel\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: last_name\n  value_before_type_cast: Guérin\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: gender\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: description\n  value_before_type_cast: sdfkjfkljfdsklfjdslkfjsd\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: admin\n  value_before_type_cast: false\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n
  name: invitation_token\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invitation_created_at\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invitation_sent_at\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invitation_accepted_at\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invitation_limit\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invited_by_type\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: invited_by_id\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: sash_id\n  value_before_type_cast: 21\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: level\n  value_before_type_cast: 0\n- !ruby/object:ActiveModel::Attribute::FromDatabase\n  name: download_count\n  value_before_type_cast: 0\nnew_record: false\nactive_record_yaml_version: 2\n"], ["created_at", "2020-07-01 12:44:12.635450"], ["updated_at", "2020-07-01 12:44:12.635450"]]
   (3.5ms)  COMMIT
  Merit::Action Load (22.4ms)  SELECT "merit_actions".* FROM "merit_actions" WHERE "merit_actions"."processed" = $1 ORDER BY "merit_actions"."id" ASC LIMIT $2  [["processed", false], ["LIMIT", 1000]]
   (5.7ms)  BEGIN
  Merit::Action Update (1.1ms)  UPDATE "merit_actions" SET "processed" = $1, "updated_at" = $2 WHERE "merit_actions"."id" = $3  [["processed", true], ["updated_at", "2020-07-01 12:44:12.783133"], ["id", 43]]
   (1.1ms)  COMMIT
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Sash Load (1.3ms)  SELECT "sashes".* FROM "sashes" WHERE "sashes"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  Merit::Models::ActiveRecord::BadgesSash Load (1.9ms)  SELECT "badges_sashes".* FROM "badges_sashes" WHERE "badges_sashes"."sash_id" = $1  [["sash_id", 21]]
   (0.3ms)  BEGIN
  Merit::BadgesSash Create (4.7ms)  INSERT INTO "badges_sashes" ("badge_id", "sash_id", "created_at") VALUES ($1, $2, $3) RETURNING "id"  [["badge_id", 51], ["sash_id", 21], ["created_at", "2020-07-01 12:44:12.978322"]]
   (0.6ms)  COMMIT
   (0.3ms)  BEGIN
  Merit::ActivityLog Create (2.1ms)  INSERT INTO "merit_activity_logs" ("action_id", "related_change_type", "related_change_id", "description", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["action_id", 43], ["related_change_type", "Merit::Models::ActiveRecord::BadgesSash"], ["related_change_id", 3], ["description", "a obtenu le badge Amical"], ["created_at", "2020-07-01 12:44:13.049222"]]
   (1.0ms)  COMMIT
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 21], ["LIMIT", 1]]
Completed 302 Found in 1899ms (ActiveRecord: 86.6ms | Allocations: 84003)
```

**Comment by tute** [comment]
> I don't know if this is important but I am also using Devise confirmation.

aha! There's a note in [the wiki](https://github.com/merit-gem/merit/wiki/How-to-grant-badges-on-user-using-Devise) about that. See https://github.com/merit-gem/merit/issues/164#issuecomment-134585025.

You can hook that badge to `users/confirmation#create` and the instance variable should be called `@confirmation`. Feel free to add to the wiki page this case.

Closing this issue as it's not an issue with merit, but feel free to continue the conversation.

**Comment by tute** [comment]
> I don't know if this is important but I am also using Devise confirmation.

aha! There's a note and instructions [in the wiki](https://github.com/merit-gem/merit/wiki/How-to-grant-badges-on-user-using-Devise#after-the-confirmation-action) about that.

You can hook that badge to `users/confirmation#create` and the instance variable should be called `@confirmation`.

Closing this issue as it's not an issue with merit, but feel free to continue the conversation.
